### ISSUE TITLE
getting error as

### ISSUE THREAD

**Issue by ammu11** [JunshengFu/autonomous-driving-lane-departure-warning#6]
Traceback (most recent call last):
  File "C:\lane_direction\main.py", line 34, in <module>
    clip = clip1.fl_image(process_frame) #NOTE: it should be in BGR format
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\moviepy\video\VideoClip.py", line 506, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\moviepy\Clip.py", line 137, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-57>", line 2, in set_make_frame
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\moviepy\video\VideoClip.py", line 661, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\moviepy\Clip.py", line 137, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\moviepy\video\VideoClip.py", line 506, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "C:\lane_direction\lane.py", line 592, in process_frame
    detector(binary_sub, ploty, visualization)
  File "C:\lane_direction\lane.py", line 544, in detector
    left_fit, right_fit = full_search(binary_sub, visualization=visualization)
  File "C:\lane_direction\lane.py", line 286, in full_search
    left_fit = np.polyfit(lefty, leftx, 2)
  File "C:\Users\araparthi\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\polynomial.py", line 555, in polyfit
    raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x

**Comment by RamaManiKamana21** [comment]
i am too getting the same error. Did u fix it!!... If yes please help me in fixing that : )
